import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ShopContextProvider from "@/context/ShopContext";
import Categories from "@/components/Categories";
import ToastProvider from "@/components/ToastProvider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ShopContextProvider>
          <div className="h-screen overflow-y-auto bg-[#F7F7FA]">
            <ToastProvider />
            <Navbar />
            <Categories />
            {children}
            <Footer />
          </div>
        </ShopContextProvider>
      </body>
    </html>
  );
}
