import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ShopContextProvider from "@/context/ShopContext";
import ToastProvider from "@/components/ToastProvider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import PageLoader from "@/components/PageLoader"; // ✅ Import Loader

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MeenaHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ShopContextProvider>
          <PageLoader /> {/* ✅ Shows Material UI Progress Bar */}
          <ToastProvider />
          <Header />
          {children}
          <Footer />
        </ShopContextProvider>
      </body>
    </html>
  );
}
